package shiroroku.theaurorian.DataGen;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.Tags;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;
import shiroroku.theaurorian.Registry.BlockRegistry;
import shiroroku.theaurorian.TheAurorian;

import java.util.concurrent.CompletableFuture;

public class DataGenBlocksTags extends BlockTagsProvider {

    public static final TagKey<Block> CERULEAN_ORE = BlockTags.create(new ResourceLocation(TheAurorian.MODID, "cerulean_ore"));
    public static final TagKey<Block> DUNGEON_BRICKS = BlockTags.create(new ResourceLocation(TheAurorian.MODID, "dungeon_bricks"));
    public static final TagKey<Block> DUNGEON_GATES = BlockTags.create(new ResourceLocation(TheAurorian.MODID, "dungeon_gates"));
    public static final TagKey<Block> AURORIAN_STONES = BlockTags.create(new ResourceLocation(TheAurorian.MODID, "aurorian_stones"));
    public static final TagKey<Block> MOONSTONE_ORE = BlockTags.create(new ResourceLocation(TheAurorian.MODID, "moonstone_ore"));

    protected DataGenBlocksTags(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, TheAurorian.MODID, existingFileHelper);
    }

    @Override
protected void addTags(HolderLookup.Provider provider) {
        this.tag(BlockTags.DEEPSLATE_ORE_REPLACEABLES).add(BlockRegistry.aurorian_deepslate.get());
        this.tag(BlockTags.DIRT).add(BlockRegistry.aurorian_dirt.get());
        this.tag(BlockTags.DIRT).add(BlockRegistry.aurorian_grass.get());
        this.tag(BlockTags.FLOWERS).add(BlockRegistry.bright_bulb.get());
        this.tag(BlockTags.FLOWERS).add(BlockRegistry.petunia.get());
        this.tag(BlockTags.LEAVES).add(BlockRegistry.silentwood_leaves.get());
        this.tag(BlockTags.LEAVES).add(BlockRegistry.weeping_willow_leaves.get());
        this.tag(BlockTags.LOGS_THAT_BURN).add(BlockRegistry.silentwood_log.get());
        this.tag(BlockTags.LOGS_THAT_BURN).add(BlockRegistry.weeping_willow_log.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.silentwood_chest.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.silentwood_crafting_table.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.silentwood_fence.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.silentwood_log.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.silentwood_planks.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.silentwood_slab.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.silentwood_stairs.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.silentwood_ladder.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.weeping_willow_log.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.weeping_willow_planks.get());
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(BlockRegistry.weeping_willow_stairs.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_coal_block.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_coal_ore.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_steel_block.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_stone_brick.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_stone_brick_stairs.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_stone_stairs.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_grass_light.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.cerulean_block.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.moonstone_block.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.peridotite.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.peridotite_smooth.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.peridotite_smooth_stairs.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.umbra_stone.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.umbra_stone_cracked.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.umbra_stone_roof_tiles.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.umbra_stone_roof_stairs.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_cobblestone.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_cobblestone_slab.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_cobblestone_stairs.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_cobblestone_wall.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_deepslate.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_deepslate_slab.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_deepslate_stairs.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_deepslate_wall.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_furnace.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_portal_frame.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.aurorian_stone.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.cerulean_ore.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.chimney.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.deepslate_cerulean_ore.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.deepslate_moonstone_ore.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.geode.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.moon_gem.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.moonlight_forge.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.moonstone_ore.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(BlockRegistry.scrapper.get());
        this.tag(BlockTags.MINEABLE_WITH_SHOVEL).add(BlockRegistry.aurorian_dirt.get());
        this.tag(BlockTags.MINEABLE_WITH_SHOVEL).add(BlockRegistry.aurorian_grass.get());
        this.tag(BlockTags.MINEABLE_WITH_SHOVEL).add(BlockRegistry.aurorian_farm_tile.get());
        this.tag(BlockTags.MINEABLE_WITH_SHOVEL).add(BlockRegistry.moon_sand.get());
        this.tag(BlockTags.NEEDS_STONE_TOOL).add(BlockRegistry.cerulean_ore.get());
        this.tag(BlockTags.NEEDS_STONE_TOOL).add(BlockRegistry.geode.get());
        this.tag(BlockTags.NEEDS_STONE_TOOL).add(BlockRegistry.moonstone_ore.get());
        this.tag(BlockTags.PLANKS).add(BlockRegistry.silentwood_planks.get());
        this.tag(BlockTags.PLANKS).add(BlockRegistry.weeping_willow_planks.get());
        this.tag(BlockTags.REPLACEABLE).add(BlockRegistry.aurorian_tallgrass.get());
        this.tag(BlockTags.REPLACEABLE).add(BlockRegistry.lavender_block.get());
        this.tag(BlockTags.SAPLINGS).add(BlockRegistry.silentwood_sapling.get());
        this.tag(BlockTags.SAPLINGS).add(BlockRegistry.weeping_willow_sapling.get());
        this.tag(BlockTags.SLABS).add(BlockRegistry.aurorian_cobblestone_slab.get());
        this.tag(BlockTags.SLABS).add(BlockRegistry.aurorian_deepslate_slab.get());
        this.tag(BlockTags.STAIRS).add(BlockRegistry.aurorian_cobblestone_stairs.get());
        this.tag(BlockTags.STAIRS).add(BlockRegistry.aurorian_deepslate_stairs.get());
        this.tag(AURORIAN_STONES).add(BlockRegistry.aurorian_stone.get());
        this.tag(AURORIAN_STONES).add(BlockRegistry.aurorian_cobblestone.get());
        this.tag(AURORIAN_STONES).add(BlockRegistry.aurorian_deepslate.get());
        this.tag(AURORIAN_STONES).add(BlockRegistry.peridotite.get());
        this.tag(AURORIAN_STONES).add(BlockRegistry.peridotite_smooth.get());
        this.tag(BlockTags.STAIRS).add(BlockRegistry.aurorian_stone_brick_stairs.get());
        this.tag(BlockTags.STAIRS).add(BlockRegistry.aurorian_stone_stairs.get());
        this.tag(BlockTags.STAIRS).add(BlockRegistry.peridotite_smooth_stairs.get());
        this.tag(BlockTags.STAIRS).add(BlockRegistry.runestone_stairs.get());
        this.tag(BlockTags.STAIRS).add(BlockRegistry.umbra_stone_roof_stairs.get());
        this.tag(BlockTags.STONE_ORE_REPLACEABLES).add(BlockRegistry.aurorian_stone.get());
        this.tag(BlockTags.WALLS).add(BlockRegistry.aurorian_cobblestone_wall.get());
        this.tag(BlockTags.WALLS).add(BlockRegistry.aurorian_deepslate_wall.get());
        this.tag(BlockTags.WOODEN_FENCES).add(BlockRegistry.silentwood_fence.get());
        this.tag(BlockTags.WOODEN_SLABS).add(BlockRegistry.silentwood_slab.get());
        this.tag(BlockTags.WOODEN_STAIRS).add(BlockRegistry.silentwood_stairs.get());
        this.tag(BlockTags.WOODEN_STAIRS).add(BlockRegistry.weeping_willow_stairs.get());
        this.tag(CERULEAN_ORE).add(BlockRegistry.cerulean_ore.get());
        this.tag(CERULEAN_ORE).add(BlockRegistry.deepslate_cerulean_ore.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.darkstone.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.darkstone_chipped.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.darkstone_gate.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.darkstone_gate_keyhole.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.darkstone_lamp.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.darkstone_pillar.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.darkstone_stairs.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.moon_temple_bars.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.umbra_stone.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.umbra_stone_cracked.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.umbra_stone_roof_tiles.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.umbra_stone_roof_stairs.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.moon_temple_bricks.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.moon_temple_bricks_smooth.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.moon_temple_gate.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.moon_temple_gate_keyhole.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.moon_temple_interior_gate.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.moon_temple_interior_gate_keyhole.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.moon_temple_lamp.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.runestone.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.runestone_bars.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.runestone_gate.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.runestone_gate_keyhole.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.runestone_gate_loot_keyhole.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.runestone_lamp.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.runestone_smooth.get());
        this.tag(DUNGEON_BRICKS).add(BlockRegistry.runestone_stairs.get());
        this.tag(DUNGEON_GATES).add(BlockRegistry.darkstone_gate.get());
        this.tag(DUNGEON_GATES).add(BlockRegistry.moon_temple_gate.get());
        this.tag(DUNGEON_GATES).add(BlockRegistry.moon_temple_interior_gate.get());
        this.tag(DUNGEON_GATES).add(BlockRegistry.runestone_gate.get());
        this.tag(MOONSTONE_ORE).add(BlockRegistry.deepslate_moonstone_ore.get());
        this.tag(MOONSTONE_ORE).add(BlockRegistry.moonstone_ore.get());
        this.tag(Tags.Blocks.CHESTS).add(BlockRegistry.silentwood_chest.get());
        this.tag(Tags.Blocks.CHESTS_WOODEN).add(BlockRegistry.silentwood_chest.get());
        this.tag(Tags.Blocks.FENCES_WOODEN).add(BlockRegistry.silentwood_fence.get());
        this.tag(Tags.Blocks.ORES).add(BlockRegistry.aurorian_coal_ore.get());
        this.tag(Tags.Blocks.ORES).add(BlockRegistry.geode.get());
        this.tag(Tags.Blocks.ORES).addTag(CERULEAN_ORE);
        this.tag(Tags.Blocks.ORES).addTag(MOONSTONE_ORE);
        this.tag(Tags.Blocks.ORES_COAL).add(BlockRegistry.aurorian_coal_ore.get());
    }
}
