org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=theaurorian
mod_name=The Aurorian
mod_license=MIT
mod_version=1.20.1-1.0.4
mod_group_id=shiroroku.theaurorian
mod_link=https://github.com/shiroroku/TheAurorian
mod_authors=shiroroku(elise), Music - Reexy: https://www.youtube.com/channel/UCgM9XlNy-qCOWiIGlcaeDKg https://www.fiverr.com/reexymusic
mod_description=Explore a land beyond this world, bathed in moonlight and shrouded in nature.

#https://maven.theillusivec4.top/top/theillusivec4/curios/curios-forge/
curios_version=5.14.1+1.20.1
jei_version=15.21.0.148

#https://dvs1.progwml6.com/files/maven/slimeknights/tconstruct/TConstruct/
tconstruct_version=1.20.1-3.11.2.208
mantle_version=1.20.1-1.11.110
#https://maven.blamejared.com/com/blamejared/crafttweaker/
crafttweaker_version=14.0.60
crafttweaker_annotation_version=4.0.0.21
#https://maven.blamejared.com/vazkii/patchouli/Patchouli/
patchouli_version=1.20.1-85-FORGE
