org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.20)
forge_version=43.4.6
forge_version_range=[43,)
loader_version_range=[43,)

mapping_channel=parchment
mapping_version=1.19.2-2022.11.27-1.19.2

mod_id=theaurorian
mod_name=The Aurorian
mod_license=MIT
mod_version=1.19.2-2.7.5
mod_group_id=shiroroku.theaurorian
mod_link=https://github.com/shiroroku/TheAurorian
mod_authors=shiroroku(elise), Music - Reexy: https://www.youtube.com/channel/UCgM9XlNy-qCOWiIGlcaeDKg https://www.fiverr.com/reexymusic
mod_description=Explore a land beyond this world, bathed in moonlight and shrouded in nature.

#https://maven.theillusivec4.top/top/theillusivec4/curios/curios-forge/
curios_version=1.19.2-5.1.6.3
jei_version=11.6.0.+

#https://dvs1.progwml6.com/files/maven/slimeknights/tconstruct/TConstruct/
tconstruct_version=1.19.2-3.8.5.62
mantle_version=1.19.2-1.10.48
#https://maven.blamejared.com/com/blamejared/crafttweaker/
crafttweaker_version=10.1.56
crafttweaker_annotation_version=3.0.0.16
#https://maven.blamejared.com/vazkii/patchouli/Patchouli/
patchouli_version=1.19.2-77